### ISSUE TITLE
Opening the settings page causes the application to crash

### ISSUE THREAD

**Issue by BreadKat0707** [patzly/tack-android#22]
System info: ColorOS 12.1(Android 12)
Screen Record:
https://github.com/patzly/tack-android/assets/61643570/98cffc35-8fe5-49e0-a38a-f272871a51eb

**Comment by patzly** [comment]
Thanks! I can't reproduce the crash on any of my devices and your device doesn't seem to send crashlogs over Google Play (maybe you could [enable](https://support.google.com/accounts/answer/6078260?hl=en) this so I receive the crashlog), so I need you to read the crashlog manually with an app like [Logcat](https://play.google.com/store/apps/details?id=com.tananaev.logcat) (just filter for tack or xyz.zedler.patrick.tack). Hope you can do that!

**Comment by BreadKat0707** [comment]
I've turn usage & diagnostics on and tried to use logcat
[logcat.txt](https://github.com/patzly/tack-android/files/14393045/logcat.txt)
Hope the content will be useful

**Comment by patzly** [comment]
Thanks! Now I know the reason: could you please clear the app data of Tack? You had selected a sound which I removed in this update because it sounded bad for the newly implemented subdivisions of beats and I forgot to implement a migration. Does this work?

**Comment by TL-P** [comment]
Hey, same problem here and clearing the app data worked!

**Comment by patzly** [comment]
Glad this works! I think I have to publish a small update because of that.
