### ISSUE TITLE
Translation of Chinese

### ISSUE THREAD

**Issue by llxlr** [patzly/tack-android#25]
Hi, I think two versions, Simplified Chinese (zh-Hans) and Traditional Chinese (zh-Hant), are enough to keep the application small! I wanna translate them.

**Comment by patzly** [comment]
Hi! I've read that zh-CN is also the simplified version and zh-TW the traditional, can we use them instead? Because your requested are not Android compatible, we need a code with the format xx or xx-XX and CN and TW both would match that.

**Comment by llxlr** [comment]
Alright.

**Comment by llxlr** [comment]
I'm almost done.
![image](https://github.com/patzly/tack-android/assets/33483752/8a313250-540f-4267-9125-9eca297233f6)
I also translated this part of the xml file, but it doesn't work.
```diff
-  <array name="label_tempo_terms" translatable="false">
-    <item>Largo</item>
-    <item>Larghetto</item>
-    <item>Adagio</item>
-    <item>Andante</item>
-    <item>Moderato</item>
-    <item>Allegro</item>
-    <item>Presto</item>
-    <item>Prestissimo</item>
-  </array>
+  <array name="label_tempo_terms" translatable="true">
+    <item>广板</item>
+    <item>小广板</item>
+    <item>柔板</item>
+    <item>行板</item>
+    <item>中板</item>
+    <item>快板</item>
+    <item>急板</item>
+    <item>最急板</item>
+  </array>
```

**Comment by patzly** [comment]
Ah that's because of the "translateable=false", I thought the music terms for tempo are always Italien, but there are specific translations in Chinese am I right? Then I have to change it to "true". Thank you so much for your fast contributions!

**Comment by llxlr** [comment]
OK

**Comment by patzly** [comment]
I added them to Transifex now :)

**Comment by patzly** [comment]
Thank you for translating!! I'm currently still working on the app for smartwatches, so there will be a bunch of more strings when I release the new watch app.
