### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by FragataIncognita** [patzly/tack-android#36]
Hello, I just translated this app to spanish, initially did it in the CL variant, but there is no difference with the ES one, so I imported the CL one to the ES one, just so that you know that they are the same, so you don't really need to put them both, except that in the CL one I put a little chilean idiom somewhere, but apart from that you can use whichever you prefer in the app update. CL spanish and ES spanish in this apps case are identical.

**Comment by patzly** [comment]
Hi, thank you so much for your work and your explanation! I've added both to the app, it's always better to also have a more specific variant. I also answered your question on Transifex so you can take a look at the translation. Thanks again and stay tuned for the update!
