### ISSUE TITLE
Highlight current main beat

### ISSUE THREAD

**Issue by ValYouW** [patzly/tack-android#39]
Hi, 
First of all many thanks for this app!! 

Is it possible to have the main beat highlighted so we know where we are. 
For example, if I have 4 main beats with 4 sub divisions (1e&a 2e&a 3e&a 4e&a) it would be nice the 1/2/3/4 main beats to be highlighted while playing their sub divisions. 
Thx !

**Comment by patzly** [comment]
Thanks for your suggestion!

**Comment by ValYouW** [comment]
Submitted PR #40 
I am not sure it matches to your practices but it seems to be working :)
